class UniversityParser
  UNIVERSITIES = [
    "Albany Law School",
    "American University",
    "American University Washington College of Law",
    "Baylor Law School",
    "Baylor University School of Law",
    "Benjamin N. Cardozo School of Law",
    "Boston College Law School",
    "Boston University School of Law",
    "Brigham Young University",
    "Brooklyn Law School",
    "Case Western Reserve University School of Law",
    "Catholic University of America",
    "Chicago-Kent College of Law",
    "Chicago-Kent College of Law at Illinois Institute of Technology",
    "Columbia Law School",
    "Columbia University School of Law",
    "Cornell Law School",
    "DePaul University College of Law",
    "Duke University School of Law",
    "Emory University School of Law",
    "Florida State University College of Law",
    "Fordham University School of Law",
    "George Mason University School of Law",
    "George Washington University Law School",
    "Georgetown University Law Center",
    "Georgia State University",
    "Harvard Law School",
    "Hofstra University School of Law",
    "Howard University School of Law",
    "Indiana University Maurer School of Law",
    "Indiana University Robert H. McKinney School of Law",
    "Loyola Law School",
    "Loyola Law School, Los Angeles",
    "Loyola Marymount University",
    "Loyola University Chicago School of Law",
    "Mitchell Hamline School of Law",
    "New York Law School",
    "New York University School of Law",
    "Northeastern University School of Law",
    "Northwestern Pritzker School of Law",
    "Notre Dame Law School",
    "Osgoode Hall Law School",
    "Pace University School of Law",
    "Pepperdine University",
    "Pepperdine University School of Law",
    "Rutgers Law School",
    "SMU Dedman School of Law",
    "Santa Clara University School of Law",
    "Seattle University School of Law",
    "Seton Hall University School of Law",
    "South Texas College of Law",
    "Southern Methodist University",
    "Southern Methodist University Dedman School of Law",
    "St. John's University School of Law",
    "St. John’s University School of Law",
    "Stanford Law School",
    "Suffolk University Law School",
    "Syracuse University College of Law",
    "Temple University",
    "Temple University Beasley School of Law",
    "Texas Tech University School of Law",
    "The Catholic University of America",
    "The Ohio State University Moritz College of Law",
    "Tulane University Law School",
    "University of California, Berkeley, School of Law",
    "University of California, Hastings College of the Law",
    "University of California, Los Angeles",
    "University of California, Los Angeles, School of Law",
    "University of Southern California Law School",
    "University of California",
    "University of Chicago Law School",
    "University of Colorado Law School",
    "University of Connecticut School of Law",
    "University of Florida",
    "University of Florida Levin College of Law",
    "University of Georgia",
    "University of Georgia School of Law",
    "University of Houston Law Center",
    "University of Illinois",
    "University of Illinois College of Law",
    "University of Iowa College of Law",
    "University of Maryland Francis King Carey School of Law",
    "University of Maryland School of Law",
    "University of Miami School of Law",
    "University of Michigan Law School",
    "University of Minnesota Law School",
    "University of North Carolina School of Law",
    "University of Oklahoma College of Law",
    "University of Oregon School of Law",
    "University of Pennsylvania Law School",
    "University of Pittsburgh School of Law",
    "University of Richmond School of Law",
    "University of San Diego",
    "University of San Diego School of Law",
    "University of San Francisco School of Law",
    "University of Southern California Gould School of Law",
    "University of Southern California",
    "University of Tennessee College of Law",
    "University of Texas School of Law",
    "University of Toronto",
    "University of Toronto Faculty of Law",
    "University of Virginia School of Law",
    "University of Washington School of Law",
    "University of Wisconsin Law School",
    "Vanderbilt Law School",
    "Villanova University Charles Widger School of Law",
    "Villanova University School of Law",
    "Wake Forest University School of Law",
    "Washington University School of Law",
    "Washington University in St. Louis",
    "Washington University in St. Louis, School of Law",
    "Washington and Lee University School of Law",
    "William & Mary Law School",
    "Yale Law School",
    "University of Auckland",
    "Northwestern University School of Law",
    "Northwestern University Law School",
    "Harvard University",
    "Tel Aviv University",
    "Nelson Mandela University",
    "Victoria University Faculty of Law",
    "Northwestern University Pritzker School of Law",
    "McGill University Faculty of Law",
    "University of British Columbia",
    "Victoria University of Wellington",
    "The University of Sydney, Australia",
    "University of Melbourne",
    "McMaster University",
    "Murdoch University",
    "University of Mumbai",
    "Nalsar University of Law",
    "Stellenbosch University",
    "UCLA School of Law",
    "Vanderbilt University Law School",
    "University of Pennsylvania School of Law",
    "Peking University Law School",
    "CUNY School of Law",
    "Chuo University",
    "University of Amsterdam Law School",
    "University of the District of Columbia David A. Clarke School of Law",
    "London School of Economics and Political Science",
    "Rutgers School of Law - Newark",
    "University of Sydney Law School",
    "DePaul University",
    "Yale University",
    "New York University",
    "University of Western Australia",
    "Cornell University Law School",
    "Columbia University",
    "Rutgers University School of Law",
    "Georgetown University",
    "Tel-Aviv University",
    "King's College London",
    "Universidad del Valle de México",
    "University of Milan",
    "Vanderbilt University School of Law",
    "University of Natal School of Law",
    "Georgetown Law School",
    "University of Chicago",
    "Washington & Lee University School of Law",
    "University of Michigan",
    "Northwestern University",
    "University of Pennsylvania",
    "The George Washington University",
    "Stanford University Law School",
    "University of Arizona",
    "Fordham University",
    "University of Pennsylvania Carey Law School",
    "Duke University",
    "Indiana University School of Law",
    "University of Alabama School of Law",
    "University of Virginia",
    "University of Alberta",
    "John Marshall Law School",
    "The Chinese University of Hong Kong",
    "Cornell University",
    "University of Missouri School of Law",
    "Hastings College of the Law",
    "Monash University",
    "Boston University",
    "Saint Louis University School of Law",
    "Vanderbilt University",
    "Vermont Law School",
    "Western University",
    "University of Cincinnati College of Law",
    "University of Kansas School of Law",
    "State University of New York at Buffalo School of Law",
    "University of Tulsa College of Law",
    "University of Nottingham",
    "Washington University",
    "China University of Political Science and Law",
    "Shanghai Jiao Tong University",
    "Marquette University",
    "McGill University",
    "University of Washington",
    "University of Denver Sturm College of Law",
    "Yonsei University Department of Medical Law and Ethics",
    "Lewis & Clark Law School",
    "Pennsylvania State University Dickinson School of Law",
    "Universidad de Alcalá",
    "Universidad Nacional de La Plata",
    "Universidad Torcuato Di Tella",
    "Jinan University",
    "Chapman University",
    "University College London",
    "Cardozo Law School",
    "George Washington University",
    "Quinnipiac University School of Law",
    "University of Ottawa",
    "University of Cambridge",
    "Louisiana State University Paul M. Hebert Law Center",
    "Charleston School of Law",
    "Santa Clara University",
    "Michigan State College of Law",
    "Maurice A. Deane School of Law at Hofstra University",
    "West Virginia University College of Law",
    "Stetson University",
    "University of Connecticut",
    "Francisco Marroquín University",
    "University of Witwatersrand",
    "University of Kentucky College of Law",
    "University of Sydney",
    "Stanford University",
    "University of New Hampshire",
    "University of Denver Sturm College of Law",
    "Antonin Scalia Law School",
    "Fudan University Law School",
    "UC Hastings College Of The Law",
    "Renmin University of China",
    "Drake University",
    "University of Windsor",
    "University of New South Wales",
    "University of Utah S.J. Quinney College of Law",
    "Heinrich Heine University",
    "The University of Texas at Austin",
    "University of Missouri - Columbia School of Law",
    "The University of Hong Kong",
    "University of Pretoria",
    "University of Missouri",
    "London University",
    "Cambridge University",
    "University of New Mexico School of Law",
    "Keio University",
    "Nanjing University",
    "Cleveland State University - Marshall College of Law",
    "Comillas Pontifical University",
    "Ohio State University Moritz College of Law",
    "University of Paris II (Panthéon-Assas)",
    "George Washington University Articles Editor",
    "University of Cape Town School of Law",
    "Leiden University",
    "Georgetown Law School",
    "National Law University, Jodhpur",
    "Universidad Iberoamericana",
  ]

  def self.parse(string)
    # string = "J.D., Columbia Law School, 1987"
    # string = 'University of California, Berkeley, School of Law'


    universities = UNIVERSITIES.sort_by!(&:length).reverse!

    matched_university = universities.find do |university|
      string.gsub(/,\s*/, ' ').include?(university.gsub(/,\s*/, ' '))
    end

    matched_university
  end
end
